extends:
  - next
  - next/core-web-vitals
  - jest
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:jest/recommended
  - plugin:jest/style
globals:
  React: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  project: '**/tsconfig.json'
plugins:
  - '@typescript-eslint'
rules:
  no-unused-vars: error
  no-console: error
  no-use-before-define: error
  no-irregular-whitespace:
    - error
    - skipTemplates: true
  jsx-quotes:
    - 'error'
    - 'prefer-double'
  '@typescript-eslint/no-unused-vars': error
  '@typescript-eslint/no-explicit-any': 'warn'
  '@typescript-eslint/consistent-type-imports': 'error'
overrides:
  - files:
      - '*.ts'
      - '*.tsx'
    parserOptions:
      project: '**/tsconfig.json'
    rules:
      '@typescript-eslint/prefer-nullish-coalescing': error
